apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend-streaming
  name: backend-streaming
spec:
  type: NodePort
  ports:
    - name: "50052"
      port: 50052
      targetPort: 50052
    - name: "8083"
      port: 8083
      targetPort: 8081
      nodePort: 30020
  selector:
    app: backend-streaming
