apiVersion: batch/v1
kind: Job
metadata:
  name: mc-streaming
spec:
  template:
    spec:
      containers:
        - command:
            - "/bin/sh"
            - "-c"
            - "until (/usr/bin/mc config host add myminio http://${MINIO_ENDPOINT} ${MINIO_USER} ${MINIO_PASSWORD}) do echo '...waiting...' && sleep 1; done; /usr/bin/mc mb --ignore-existing myminio/${MINIO_BUCKET}; /usr/bin/mc event remove --event put myminio/${MINIO_BUCKET} arn:minio:sqs::PRIMARY:postgresql; /usr/bin/mc event add --event put myminio/${MINIO_BUCKET} arn:minio:sqs::PRIMARY:postgresql; exit 0;"
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          env:
            - name: MINIO_BUCKET
              valueFrom:
                configMapKeyRef:
                  key: MINIO_BUCKET
                  name: backend-streaming-env
            - name: MINIO_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  key: MINIO_ENDPOINT
                  name: backend-streaming-env
            - name: MINIO_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: MINIO_PASSWORD
                  name: backend-streaming-env
            - name: MINIO_USER
              valueFrom:
                configMapKeyRef:
                  key: MINIO_USER
                  name: backend-streaming-env
          image: minio/mc
          name: mc-streaming
      restartPolicy: OnFailure
  backoffLimit: 4
