apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: minio-streaming-data
  name: minio-streaming-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
