apiVersion: v1
kind: Service
metadata:
  labels:
    app: minio-streaming
  name: minio-streaming
spec:
  type: NodePort
  ports:
    - name: "8090"
      port: 8090
      targetPort: 8090
      nodePort: 30023
    - name: "9000"
      port: 9000
      targetPort: 9000
  selector:
    app: minio-streaming
