apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-streaming
  name: nginx-streaming
spec:
  type: NodePort
  ports:
    - name: "9000"
      port: 9000
      targetPort: 9000
      nodePort: 30022
  selector:
    app: nginx-streaming
