apiVersion: v1
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }

    http {
        sendfile on;
        client_max_body_size 20M;

        server {
            listen 9000;

            location / {
                proxy_pass http://minio-streaming:9000;
            }
        }
    }
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    app: nginx-streaming
  name: nginx-streaming
