apiVersion: v1
data:
  nginx.conf: |
    events {
      worker_connections 1024;
    }

    http {
      sendfile on;
      client_max_body_size 20M;

      server {
          listen 9000 ssl;

          ssl_certificate /etc/nginx/tls/cert.pem;
          ssl_certificate_key /etc/nginx/tls/key.pem;

          location / {
              proxy_pass http://minio-streaming:9000;
          }
      }
    }

kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    app: nginx-streaming
  name: nginx-streaming
