apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgres-streaming
  name: postgres-streaming
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-streaming
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres-streaming
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_DB
                  name: backend-streaming-env
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PASSWORD
                  name: backend-streaming-env
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USER
                  name: backend-streaming-env
          image: postgres:16.4-alpine
          livenessProbe:
            exec:
              command:
                - "/bin/sh"
                - "-c"
                - "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
            failureThreshold: 3
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 10
          name: postgres-streaming
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-streaming-data
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
      restartPolicy: Always
      volumes:
        - name: postgres-streaming-data
          persistentVolumeClaim:
            claimName: postgres-streaming-data
