env: local
database_url: postgres://postgres:postgres@localhost:5432/drop-audiostreaming
jwt_secret: secret
grpc_port: localhost:50052
http_port: localhost:8081
verification_secret: secret # secret for url verification
url_ttl: 2000 # url ttl in minutes
minio:
  password: minioadmin
  user: minioadmin
  url: 127.0.0.1:9000
  bucket: drop-audio
  use_ssl: false
  location: us-east-1
grpc_client:
  retries: 3
  timeout: 100s
  port: localhost:50051
file_size_limit: 10000000 # 10MB
archive_size_limit: 100000000 # 100MB
image_size_limit: 1000000 # 1MB